'use strict';
const assert=require('node:assert/strict');
const {buildDomainSnapshots,day}=require('../lib/domain-model.cjs'),{fixture}=require('./domain-fixtures.cjs');
const {input,put}=fixture();
put('finSales',{'วันที่ขายสินค้า (กรอก)':'2026-09-01','มูลค่ารวม (ห้ามแก้ไข)':100,'ชื่อลูกค้า (เลือก)':'DEMO','Credit Day (ห้ามแก้ไข)':30,'วันที่ต้องได้รับเงิน (ห้ามแก้ไข)':'2026-09-20','สถานะ (ห้ามแก้ไข)':'ยังไม่ได้รับเงิน'});
put('finSales',{'วันที่ขายสินค้า (กรอก)':'2026-09-01','มูลค่ารวม (ห้ามแก้ไข)':50,'ชื่อลูกค้า (เลือก)':'DEMO','วันที่ต้องได้รับเงิน (ห้ามแก้ไข)':'2026-09-20','วันที่ได้รับเงินจริง (กรอก)':'2026-09-10','สถานะ (ห้ามแก้ไข)':'รับเงินเรียบร้อย'});
put('finSales',{'วันที่ขายสินค้า (กรอก)':'2026-09-01','ชื่อลูกค้า (เลือก)':'DEMO unknown amount','สถานะ (ห้ามแก้ไข)':'ยังไม่ได้รับเงิน'});
put('finPurchases',{'วันที่ (กรอก)':'2026-09-01','มูลค่ารวม (ห้ามแก้ไข)':70,'Supplier (เลือก)':'DEMO','Credit Day (ห้ามแก้ไข)':15,'วันที่ต้องจ่าย (ห้ามแก้ไข)':'2026-09-15','สถานะ (ห้ามแก้ไข)':'ยังไม่ชำระเงิน'});
put('finExpenses',{'วันที่ (กรอก)':'2026-09-02','รายการ (เลือก)':'DEMO correction','มูลค่ารวม (ห้ามแก้ไข)':-2.01,'วันที่โอนเงิน (กรอก)':'2026-09-03'});
put('pr',{'วันที่เปิด PR':'2026-09-01','รายการ':'DEMO unknown receipt','จำนวน':10,'ราคา':2,'TOTAL':20,'PO NO.':'DEMO-PO1','สถานะ':'เปิด PO'});
put('pr',{'วันที่เปิด PR':'2026-09-01','รายการ':'DEMO explicit receipt','จำนวน':10,'ราคา':2,'TOTAL':20,'PO NO.':'DEMO-PO2',"Q'TY":4,'สถานะ':'เปิด PO'});
put('pr',{'วันที่เปิด PR':'2026-09-01','รายการ':'DEMO zero','จำนวน':10,'ราคา':2,'TOTAL':20,'PO NO.':'DEMO-PO3',"Q'TY":10,'สถานะ':'เปิด PO'});
for(const [id,op,ok,ng,state,date] of [['A','OP1',10,0,'ACTIVE','2026-09-10'],['B','OP2',8,null,'ACTIVE','2026-09-10'],['C','OP1',999,0,'DELETED','2026-09-10'],['D','OP1',100,0,'ACTIVE',0]])put('production',{'วันที่ผลิต':date,'เครื่องจักร':'DEMO-M','Job no.':'DEMO-J','Part no.':'DEMO-P','Customer':'DEMO-C','OK':ok,'NG':ng,'OP':op,'PR Record ID':id,'PR Record Status':state});
put('ng',{'Date':0,'Job No.':'DEMO-OLD','จำนวนที่พบ':1});
put('oeeDaily',{date:'2026-09-10',machine:'DEMO-M',oeeStatus:'WAITING',oee:null,quality:null});
put('st',{ST_Key:'DEMO-ST',Official_ST_Sec:30,Evidence_Mode:'LEGACY_BASELINE',Status:'ACTIVE'});
put('prices',{'Customer':'DEMO-C','Part no.':'DEMO-P','ราคาต่อชิ้น':2.25});
const movement=(id,action,qty,extra={})=>put('plating',{'Transaction ID':id,'Timestamp':'2026-09-10','Action':action,'Job No.':'DEMO-J','DWG. No.':'DEMO-P','Customer':'DEMO-C','Supplier':'DEMO-S','Qty':qty,...extra});
movement('P1','ส่งออกไปชุบ',20);movement('P2','รับกลับจากชุบ',5);movement('P3','รับกลับจากชุบ',3);movement('P4','ยกเลิกรายการ',3,{'Cancel Ref Transaction ID':'P3','Cancel Original Action':'รับกลับจากชุบ'});
const before=JSON.stringify(input),snapshots=buildDomainSnapshots(input),card=id=>snapshots.find(s=>s.card_id===id&&s.month==='2026-09');
assert.equal(JSON.stringify(input),before,'all inputs must be immutable');
assert.equal(day(0),null);assert.equal(day('2026-02-30'),null);
assert.equal(card('ar').value_numeric,100);assert.equal(card('ar').rows.length,2);assert.equal(card('ar').value_status,'PARTIAL_UNBOUNDED');
assert.equal(card('ap').value_numeric,70,'NFKC Thai unpaid status');
assert.equal(card('creditAp').value_numeric,15);assert.equal(card('ar').rows[0].fields.overdueDays,9);
assert.equal(card('finReceived').value_numeric,null,'unreconciled sources cannot become bank cash');assert.equal(card('finReceived').summary.groups[0].knownSubtotalMinor,5000);
assert.equal(card('finPaid').summary.groups[0].knownSubtotalMinor,-201,'negative adjustments preserved even if account missing');
assert.equal(card('purchase').rows[0].fields.received,null);assert.equal(card('purchase').rows[0].valueMinor,null);
assert.equal(card('purchase').rows[1].fields.balance,6);assert.equal(card('purchase').rows[1].valueMinor,1200);assert.equal(card('purchase').rows[2].valueMinor,0);assert.equal(card('purchase').value_numeric,12);
assert.equal(card('productionRegister').rows.length,2,'deleted and undated rows excluded from month');assert.deepEqual(card('productionRegister').summary.groups.map(g=>[g.name,g.ok]),[['OP1',10],['OP2',8]]);assert.equal(card('productionRegister').summary.groups[1].unknownNg,1);
assert.equal(card('productionUnassigned').rows.length,2,'undated facts remain reviewable');
assert.equal(card('capacity').value_numeric,25,'use committed trusted load, not stale/full/review load');assert.equal(card('capacityLines').rows[0].fields.noOtHours,640);assert.equal(card('capacityLines').rows[0].fields.normalHours,920);
assert.equal(card('oee').value_numeric,null);assert.equal(card('oeeDaily').rows[0].fields.q,null);assert.equal(card('standardTime').rows[0].fields.output8,960);
assert.equal(card('plating').rows[0].fields.qty,15);assert.equal(card('plating').value_numeric,33.75);assert.equal(card('platingMovements').rows.length,4);
assert.equal(card('productionForecast').value_numeric,null,'missing reporting mode, complete calendar and shift evidence block forecasts');assert.equal(card('qaInspection').value_numeric,null,'empty QA is not zero defects');
const bad=structuredClone(input);bad.sources.capacity.values.push(bad.sources.capacity.values.at(-1));assert.throws(()=>buildDomainSnapshots(bad),/CAPACITY_DUPLICATE_PERIOD/);
const renamed=structuredClone(input);renamed.sources.finSales.values[0][5]='changed';assert.throws(()=>buildDomainSnapshots(renamed),/HEADER_MISSING/);
const incomplete=structuredClone(input);incomplete.sources.finSales.complete=false;assert.throws(()=>buildDomainSnapshots(incomplete),/INCOMPLETE_SOURCE/);
const double=structuredClone(input);double.sources.plating.values.push([...double.sources.plating.values.at(-1)]);assert.equal(buildDomainSnapshots(double).find(s=>s.card_id==='plating').value_numeric,null,'duplicate cancellation invalidates balance');
console.log('PASS: private domain scope, cash evidence vs bank cash, negative/unknown/zero, Thai statuses, PR receipt bounds, OP/deletion/date isolation, committed capacity, empty OEE/QA, exact plating reversal, headers and source completeness');
