'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const {buildExpenseSnapshots,amount}=require('../lib/expense-model.cjs');
const headers=['เดือน','ต้นทุน','รายการต้นทุน','จำนวนเงิน','ประเภทต้นทุนหลัก','เดือน (ตัวเลข)','ปี','บริษัท'];
const source={spreadsheetId:'DEMO-SYNTHETIC',gid:123,tab:'DEMO expenses',readAt:'2026-09-28T08:00:00Z',values:[headers]};
const row=(n,company='P&T',month=2,item='DEMO Tool')=>[['Jan','Feb','Mar'][month-1]||'invalid','DEMO category',item,n,'DEMO type',month,2026,company];
for(const [input,expected] of [[null,null],['',null],[' ',null],['x',null],['1,23',null],[0,0],[-1.005,-101],[1.005,101],['1,234.56',123456],[true,null]])assert.equal(amount(input),expected);
assert.throws(()=>amount(1e20),/MONEY_RANGE/);
source.values.push(row(100.005),row(-1.005),row(0),row(9,''),row(null),row(777,'TSP'),row(888,'P&T',13));
const [feb,mar]=buildExpenseSnapshots(source,['2026-02','2026-03'],'2026-09-28');
assert.equal(feb.summary.rows,5);assert.equal(feb.summary.knownSubtotalMinor,9900);assert.equal(feb.summary.reviewKnownMinor,900);
assert.equal(feb.summary.unknownAmountRows,1);assert.equal(feb.summary.scope.unassignedCompanyRows,1);assert.equal(feb.summary.scope.unassignedPeriodRows,1);assert.equal(feb.summary.scope.excludedOtherCompanyRows,1);
assert.equal(feb.rows.find(r=>!r.company).valueMinor,null);assert.equal(feb.rows[0].source.row,2);assert.equal(feb.rows[2].valueMinor,0);
assert.equal(feb.value_status,'PARTIAL_UNBOUNDED');assert.equal(mar.value_numeric,null);assert.equal(mar.value_status,'NO_PERIOD_DATA');
assert.equal(feb.summary.groups[0].knownSubtotalMinor,9900);assert.equal(feb.summary.groups[0].rows,5);assert.equal(feb.production_accepted,false);
assert.equal(buildExpenseSnapshots(source,['2026-02'],'2026-09-28')[0].content_hash,feb.content_hash);
assert.throws(()=>buildExpenseSnapshots(source,['2026-02'],'2026-02-30'),/INVALID_AS_OF/);
assert.throws(()=>buildExpenseSnapshots(source,['2026-10'],'2026-09-28'),/INVALID_MONTH/);
assert.throws(()=>buildExpenseSnapshots({...source,values:[headers.slice(0,-1)]},['2026-02'],'2026-09-28'),/HEADER/);
const conflict=row(111);conflict[0]='Mar';const [bad]=buildExpenseSnapshots({...source,values:[headers,conflict]},['2026-02'],'2026-09-28');
assert.equal(bad.value_numeric,null);assert.equal(bad.rows[0].status,'REVIEW');assert.ok(bad.rows[0].issues.includes('PERIOD_CONFLICT'));
const [duplicate]=buildExpenseSnapshots({...source,values:[headers,row(10),row(10)]},['2026-02'],'2026-09-28');
assert.equal(duplicate.value_numeric,20,'no undocumented deduplication without an invoice key');
const [blank]=buildExpenseSnapshots({...source,values:[headers,row(10,'')]},['2026-02'],'2026-09-28');assert.equal(blank.value_numeric,null);assert.equal(blank.value_status,'UNKNOWN_VALUE');
// Business confirmation is bound to exact source content and selected rows/month.
const {createHash}=require('node:crypto');
const approvalSource={...source,values:[headers,row(10,''),row(20,'',3),row(null,''),row(30,'TSP')]};
const original=JSON.stringify(approvalSource.values);
const confirmation={id:'DEMO-APPROVAL',company:'P&T',month:'2026-02',confirmedAt:'2026-09-28T09:00:00Z',statement:'DEMO user confirms selected rows',sourceContentHash:createHash('sha256').update(original).digest('hex'),sourceRows:[2,4]};
const approvedSource={...approvalSource,companyConfirmations:[confirmation]};
const [confirmed,otherMonth]=buildExpenseSnapshots(approvedSource,['2026-02','2026-03'],'2026-09-28');
assert.equal(JSON.stringify(approvalSource.values),original,'source cells are never overwritten');
assert.equal(confirmed.value_numeric,10);assert.equal(confirmed.summary.valuedRows,1);assert.equal(confirmed.summary.reviewRows,1);
assert.equal(confirmed.summary.scope.companyConfirmedRows,2);assert.equal(confirmed.summary.scope.unassignedCompanyRows,0);
assert.equal(confirmed.rows[0].sourceCompany,'');assert.equal(confirmed.rows[0].company,'P&T');assert.equal(confirmed.rows[0].companyConfirmation.id,confirmation.id);
assert.deepEqual(confirmed.rows[1].issues,['AMOUNT_MISSING'],'confirmation never invents missing money');
assert.equal(otherMonth.value_numeric,null);assert.equal(otherMonth.summary.scope.unassignedCompanyRows,1);
assert.equal(confirmed.summary.scope.excludedOtherCompanyRows,1);assert.equal(confirmed.production_accepted,false);assert.equal(confirmed.summary.businessCertified,false);
for(const patch of [{sourceContentHash:'0'.repeat(64)},{company:'TSP'},{sourceRows:[2,2]},{sourceRows:[3]},{sourceRows:[5]},{sourceRows:[999]}])assert.throws(()=>buildExpenseSnapshots({...approvalSource,companyConfirmations:[{...confirmation,...patch}]},['2026-02'],'2026-09-28'),/CONFIRMATION/);
const changed=JSON.parse(JSON.stringify(approvedSource));changed.values[1][3]=11;assert.throws(()=>buildExpenseSnapshots(changed,['2026-02'],'2026-09-28'),/CONFIRMATION/);
assert.notEqual(confirmed.content_hash,buildExpenseSnapshots(approvalSource,['2026-02'],'2026-09-28')[0].content_hash);
// Exercise the actual UI comparison functions, including cross-year and incomplete baselines.
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');new vm.Script(html.match(/<script>([\s\S]*?)<\/script>/)[1]);
const cards=new Map(),context={ceoCard:(_,month)=>cards.get(month)};vm.createContext(context);
vm.runInContext(html.slice(html.indexOf('  function expenseShift('),html.indexOf('  function expenseDashboard(')),context);
function card(month,minor){return {...duplicate,expense_snapshot_id:'DEMO-'+month,month,summary:{...duplicate.summary,knownSubtotalMinor:minor,groups:[{mainType:'type',category:'category',item:'DEMO tool',reviewRows:0,knownSubtotalMinor:minor}]}};}
cards.set('2026-02',card('2026-02',10000));cards.set('2026-01',card('2026-01',20000));cards.set('2025-12',card('2025-12',30000));
const current=card('2026-03',12000);assert.equal(context.expenseShift('2026-01',-1),'2025-12');
assert.equal(context.expenseComparison(current,[-1]).pct,20);assert.equal(context.expenseComparison(current,[-1,-2,-3]).base,20000);
assert.equal(context.expenseComparison(current,[-1,-2,-3]).delta,-8000);assert.equal(context.expenseComparison(current,[-12]).delta,null);
assert.equal(context.expenseChanges(current)[0].delta,2000);
cards.get('2026-02').basis='OTHER';assert.equal(context.expenseChanges(current).length,0);assert.equal(context.expenseComparison(current,[-1]).delta,null);
cards.set('2026-02',card('2026-02',0));assert.equal(context.expenseComparison(current,[-1]).pct,null);assert.equal(context.expenseComparison(current,[-1]).delta,12000);
cards.get('2026-02').summary.reviewRows=1;assert.equal(context.expenseComparison(current,[-1]).delta,null);
assert.equal(context.expenseKnown({...current,value_status:'BLOCKED'}),false);assert.equal(context.expenseKnown({...current,summary:{...current.summary,knownSubtotalMinor:NaN}}),false);
console.log('PASS: expense cents/signs/zero, company/month isolation, missing amounts, duplicate preservation, source rows, incomplete/comparable baselines and zero denominator');
